spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examplesdb?useUnicode=true&lacalTimezone=Aisa/Seoul
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect # 8버전 MySql용 SQL문을 생성해준다.
    open-in-view: false


